apiVersion: v1
kind: application
metadata: 
  name: app
spec:
  destination: 
    namespace: single-git-source
    server: https://kubernetes.default.svc
  source: 
    path: git-sources
    repourl: https://github.com/NaveenBalagouni/testing-argocd
    targetRevision: HEAD
  
  project: default
 
